# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 06:56
from __future__ import unicode_literals

import auction.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_desc', models.TextField(blank=True)),
                ('sale_time', models.DateTimeField(blank=True, null=True)),
                ('fair_market_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('is_purchased', models.BooleanField(default=False)),
                ('item_number', models.PositiveIntegerField(db_index=True, default=auction.models.item_number_generator, unique=True)),
                ('scheduled_sale_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100)),
                ('uses_item_inventory', models.BooleanField(default=False)),
                ('can_adjust_fmv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_num', models.CharField(db_index=True, default=auction.models.buyer_number_generator, max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address_line1', models.CharField(help_text='Example: 21075 425 St', max_length=50, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Marion, SD', max_length=50, verbose_name='Address Line 2')),
                ('address_line3', models.CharField(blank=True, help_text='57043', max_length=50, verbose_name='Address Line 3')),
                ('phone1', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], default='CHECK', help_text='The method or type of payment made.', max_length=6)),
                ('transaction_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Record any notes about the payment.')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='auction.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='PricedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_desc', models.TextField(blank=True)),
                ('sale_time', models.DateTimeField(blank=True, null=True)),
                ('fair_market_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('is_purchased', models.BooleanField(default=False)),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Booth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('state', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='UNPAID', max_length=7)),
                ('transaction_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='auction.Buyer')),
            ],
        ),
        migrations.AddField(
            model_name='priceditem',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Purchase'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Booth'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Purchase'),
        ),
    ]
