# Generated by Django 2.0.2 on 2018-03-09 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='donor',
            field=models.ForeignKey(blank=True, help_text='The patron/donor for tax receipt purposes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='auction.Patron'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='donor_display',
            field=models.CharField(blank=True, help_text="How the item's donor would be displayed to the public", max_length=50, null=True, verbose_name='Displayed Donor Name'),
        ),
        migrations.AddField(
            model_name='auctionitemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auction.AuctionItem'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionitemimage',
            unique_together={('item', 'sort_order')},
        ),
    ]
