# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 16:47
from __future__ import unicode_literals

import auction.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_desc', models.TextField(blank=True)),
                ('sale_time', models.DateTimeField(blank=True, null=True)),
                ('fair_market_value_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('fair_market_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=15)),
                ('item_number', models.PositiveIntegerField(db_index=True, default=auction.models.item_number_generator, unique=True)),
                ('scheduled_sale_time', models.DateTimeField(blank=True, null=True)),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Booth')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PricedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_desc', models.TextField(blank=True)),
                ('sale_time', models.DateTimeField(blank=True, null=True)),
                ('fair_market_value_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('fair_market_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=15)),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Booth')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='booth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
