# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='winning_bid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='auction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
