# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20180224_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='priceditem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
