# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20171117_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='can_adjust_fmv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booth',
            name='uses_item_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
