# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20160906_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='winning_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Bidder'),
        ),
    ]
