# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-19 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20160906_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('state', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='UNPAID', max_length=7)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Bidder')),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='winning_bidder',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Charge'),
        ),
    ]
