# Generated by Django 2.0.6 on 2018-07-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20180625_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(choices=[('MAIN', 'Main'), ('SILENT', 'Silent')], default='MAIN', help_text='Category/Group/Ring', max_length=8),
        ),
    ]
