# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20180216_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
    ]
