# Generated by Django 2.0.8 on 2018-09-22 03:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auctionitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceditem',
            name='booth',
        ),
        migrations.RemoveField(
            model_name='priceditem',
            name='purchase',
        ),
        migrations.AlterModelOptions(
            name='patron',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='is_purchased',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='purchase',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='quantity',
            field=models.CharField(blank=True, help_text='2 dozen, 3 gallons, etc.', max_length=50, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='booth',
            name='category',
            field=models.CharField(choices=[('AUCTION', 'Auction'), ('PRICED', 'Priced')], default='PRICED', max_length=8),
        ),
        migrations.AddField(
            model_name='purchase',
            name='auction_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.AuctionItem'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.Booth'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the purchase', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='fair_market_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fair Market Value', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_donation',
            field=models.BooleanField(default=False, help_text='True only when the full amount was a donation with nothing received by the Patron'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.CharField(blank=True, help_text='2 dozen, 3 gallons, etc.', max_length=50, verbose_name='Quantity'),
        ),
        migrations.DeleteModel(
            name='PricedItem',
        ),
    ]
