# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 16:30
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_booth_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=15)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], default='CHECK', max_length=6)),
                ('transaction_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='auction.Buyer')),
            ],
        ),
    ]
