# Generated by Django 2.2.1 on 2019-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20190521_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='name',
            field=models.CharField(help_text='Short but descriptive name of item.', max_length=100),
        ),
    ]
