# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='amount_currency',
        ),
        migrations.AddField(
            model_name='item',
            name='sale_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
