# Generated by Django 3.2.5 on 2021-07-15 03:12

from django.db import migrations, models


def initial_amount_total(apps, schema_editor):
    Purchase = apps.get_model('auction', 'Purchase')
    for purchase in Purchase.objects.all():
        purchase.amount_total = purchase.amount * purchase.quantity
        purchase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20210710_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.RunPython(initial_amount_total)
    ]
